---
game:
  width: 512
  height: 256
  backgroundColor: "#fff"

player:
  moves:
    retreat:
      effects:
        - lust: 2
        - backward: true
    tease:
      ranged: true
      effects:
        - lust: 4
    lunge:
      effects:
        - damage: 2
        - forward: true
    sword:
      melee: true
      effects:
        - damage: 4

  part-combinations:
    body:
      - pelvis
      - torso
    arms:2:
      - arm front
      - arm back
    legs:2:
      - leg front
      - leg back
    heads:1:
      - heads:1
      - face:1
      - hair:1
      - eyebrows:1
      - eyes:1
    cocks:medium:2:
      - cocks:medium:2
      - balls
    cocks:medium:1:
      - cocks:medium:1
      - balls
    cocks:small:2:
      - cocks:small:2
      - balls
    cocks:small:1:
      - cocks:small:1
      - balls

  hue-groups:
    hair:
      - hair:1
      - eyebrows:1
    eyes:
      - eyes:1
    skin:
      - pelvis
      - torso
      - arm front
      - arm back
      - leg front
      - leg back
      - heads:1
      - face:1
      - pussy:1
      - pussy:2
      - cocks:medium:1
      - cocks:medium:2
      - cocks:small:2
      - cocks:small:1
      - balls
      - boobs:0
      - boobs:2
      - boobs:3
      - boobs:4
